### ISSUE TITLE
Angående laboration 2

### ISSUE THREAD

**Issue by 1dv449** [johnnypesola/1dv449-jp222px-Laboration-2#1]
Hej!

Jag har nu tittat på din laboration 2.

Jag tycker det är en mycket välskriven rapport som visar på god kunskap och ett gediget arbete. Det känns som du hittat de flesta problem med applikationen och härleder dessa på ett tydligt sätt till teorin. Du uppfyller helt klart de mål som fanns för examinationen och jag sätter upp dig som G+. Bra jobbat!

Det finns ett delat dokument där man kan se de olika delar som skulle kunnat tas upp i rapporten.
https://docs.google.com/document/d/1kYNrL64Od1go4z0_sZUyIG8eFAaeFcdp95MIHsRm65A/

**Comment by johnnypesola** [comment]
Tack tack :+1:
